### ISSUE TITLE
我发现了一个小小小小bug

### ISSUE THREAD

**Issue by oblivioned** [msSj7svHwsdlKt0G/ETH-Player#1]
您好，首先很感谢贵方将这些智能合约的源码全部公开，我也很理解除了Round合约中的Settlement方法，闭源的目的，同时我也很赞成这个做法。

我已经通过区块浏览器详细分析了Settlement中资金的去向，确实如你们所说，Settlement交易未向任何地址进行转账，我由衷的感谢贵方，提供了这份合约的其他源码供我们参考学习。

在拜读源码的过程中，我发现一个微不足道的问题，它不会影响运行，我认为它属于一个笔误，在此我提出，希望能帮助到你们。

在Cost.sol，第9行
`uint256 public _costProp = 3;`

但是同样在Cost.sol中25行中的
`function WithdrawCost(uint256 value) external view returns (uint256) `
却使用了静态常量数字3，而没有使用变量 _costProp

我认为，这是一个笔误对吗？

--------------------------------- English translation by google ------------------------------
Hello, first of all, thank you for making all the source code of these smart contracts public. I also understand that in addition to the Settlement method in the Round contract, the purpose of the closed source, I also agree with this approach.

I have analyzed the whereabouts of the funds in Settlement through the block browser. As you said, the Settlement transaction has not transferred to any address. I sincerely thank you for providing other source code for this contract for our reference study. .

In the process of reading the source code, I found a trivial problem, it will not affect the operation, I think it belongs to a clerical error, I propose here, I hope to help you.

At Cost.sol, line 9
`uint256 public _costProp = 3;`

But also in the 25 lines of Cost.sol
`function WithdrawCost(uint256 value) external view returns (uint256) `
Instead of using the variable _costProp, the static constant number 3 is used.

I think this is a clerical error?

**Comment by msSj7svHwsdlKt0G** [comment]
first, thank you for the bug.

It’s true that after we checked it, we found the problem as you said, it is indeed a clerical error, and as you said, it does not affect all the functions of normal operation, we do not intend to fix this error in github, because the repair It is not necessary, the normal operation of the smart contract does not allow modification, we will not help even if the source code is modified.
